In [9]:
## 필요한 패키지 등록
import os
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

In [25]:
## 필요한 패키지 등록
import os
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

path = './data_image/'

dir_save_train = os.path.join(path, 'train')
dir_save_val = os.path.join(path, 'val')
dir_save_test = os.path.join(path, 'test')

if not os.path.exists(dir_save_train):
    os.makedirs(dir_save_train)

if not os.path.exists(dir_save_val):
    os.makedirs(dir_save_val)

if not os.path.exists(dir_save_test):
    os.makedirs(dir_save_test)

img_data = './data_image/Imgs/'
labels_data = './data_image/labels/'

nframe = len(os.listdir(img_data))

nframe_train = int(nframe * 3/4) 
nframe_val = int(nframe * 1/8) 
nframe_test = int(nframe * 1/8) 

id_frame = np.arange(nframe)
np.random.shuffle(id_frame)



# ##
offset_nframe = 0



# img_input = Image.open(os.path.join(img_data, os.listdir(img_data)[id_frame[i + offset_nframe]]))
# a = os.path.join(img_data, os.listdir(img_data)[id_frame[offset_nframe]])
# b = Image.open(a)
# print(img_input)

for i in range(nframe_train):
    img_label = Image.open(os.path.join(labels_data, os.listdir(labels_data)[id_frame[i + offset_nframe]]))
    img_input = Image.open(os.path.join(img_data, os.listdir(img_data)[id_frame[i + offset_nframe]]))


    label_ = np.asarray(img_label)
    input_ = np.asarray(img_input)

    np.save(os.path.join(dir_save_train, 'label_%03d.npy' % i), label_)
    np.save(os.path.join(dir_save_train, 'input_%03d.npy' % i), input_)

# ## 데이터 불러오기
# dir_data = './data_image/Imgs/retest'
# for i in range(20):
#     for filename in os.listdir(dir_data):
#         name_label = filename
#         img_label = Image.open(os.path.join(dir_data, name_label))
#         input_ = np.asarray(img_input)
#         np.save(os.path.join(dir_save_train, 'input_%03d.npy' % i), input_)

# for i in range(20):
#     dir_data = './data_image/labels/'
#     for filename in os.listdir(dir_data):
#         name_input = filename
#         img_input = Image.open(os.path.join(dir_data, name_input))
#         label_ = np.asarray(img_label)
#         np.save(os.path.join(dir_save_train, 'label_%03d.npy' % i), label_)


In [11]:
print(name_label)
print(ny, nx)
print(nframe)
print(img_label)
print(img_input)
print(id_frame)
print(input_)

train-labels.tif
512 512
30
<PIL.TiffImagePlugin.TiffImageFile image mode=L size=512x512 at 0x22209675A90>
<PIL.TiffImagePlugin.TiffImageFile image mode=L size=512x512 at 0x22209675F40>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 59  70  90 ... 179  97  78]
 [ 54  93 108 ...  76  75 120]
 [ 44  75  93 ...  91  77 148]
 ...
 [121 137 136 ... 202 157 122]
 [150 124 125 ... 196 131  81]
 [162 151 114 ... 114 108  84]]


In [7]:
## 데이터 불러오기
dir_data = './data_image/MT_Free'

# name_label = 'train-labels.tif'
# name_input = 'train-volume.tif'

img_label = Image.open(os.path.join(dir_data))
# img_input = Image.open(os.path.join(dir_data, name_input))

# ny, nx = img_label.size
nframe = img_label.n_frames

PermissionError: [Errno 13] Permission denied: './data_image/MT_Free'

In [20]:
import os  # 파일 이름 변경 
 
def changeName(path, cName):
    i = 397
    j = 397 
    for filename in os.listdir(path):
        if i % 2 == 0:
            print(path+filename, '=>', path+str(cName)+str(j)+'.jpg')
            os.rename(path+filename, path+str(cName)+str(j)+'.jpg')
            i += 1
            j += 1
        else:
            print(path+filename, '=>', path+str(cName)+str(j)+'.png')
            os.rename(path+filename, path+str(cName)+str(j)+'.png')
            i += 1
            

 
changeName('./data_image/MT_Free/Imgs/','test')



./data_image/MT_Free/Imgs/exp0_num_743.jpg => ./data_image/MT_Free/Imgs/test397.png
./data_image/MT_Free/Imgs/exp0_num_743.png => ./data_image/MT_Free/Imgs/test397.jpg
./data_image/MT_Free/Imgs/exp1_num_10181.jpg => ./data_image/MT_Free/Imgs/test398.png
./data_image/MT_Free/Imgs/exp1_num_10181.png => ./data_image/MT_Free/Imgs/test398.jpg
./data_image/MT_Free/Imgs/exp1_num_10334.jpg => ./data_image/MT_Free/Imgs/test399.png
./data_image/MT_Free/Imgs/exp1_num_10334.png => ./data_image/MT_Free/Imgs/test399.jpg
./data_image/MT_Free/Imgs/exp1_num_106151.jpg => ./data_image/MT_Free/Imgs/test400.png
./data_image/MT_Free/Imgs/exp1_num_106151.png => ./data_image/MT_Free/Imgs/test400.jpg
./data_image/MT_Free/Imgs/exp1_num_106729.jpg => ./data_image/MT_Free/Imgs/test401.png
./data_image/MT_Free/Imgs/exp1_num_106729.png => ./data_image/MT_Free/Imgs/test401.jpg
./data_image/MT_Free/Imgs/exp1_num_10903.jpg => ./data_image/MT_Free/Imgs/test402.png
./data_image/MT_Free/Imgs/exp1_num_10903.png => ./data

./data_image/MT_Free/Imgs/exp2_num_118897.jpg => ./data_image/MT_Free/Imgs/test565.png
./data_image/MT_Free/Imgs/exp2_num_118897.png => ./data_image/MT_Free/Imgs/test565.jpg
./data_image/MT_Free/Imgs/exp2_num_126325.jpg => ./data_image/MT_Free/Imgs/test566.png
./data_image/MT_Free/Imgs/exp2_num_126325.png => ./data_image/MT_Free/Imgs/test566.jpg
./data_image/MT_Free/Imgs/exp2_num_126814.jpg => ./data_image/MT_Free/Imgs/test567.png
./data_image/MT_Free/Imgs/exp2_num_126814.png => ./data_image/MT_Free/Imgs/test567.jpg
./data_image/MT_Free/Imgs/exp2_num_127664.jpg => ./data_image/MT_Free/Imgs/test568.png
./data_image/MT_Free/Imgs/exp2_num_127664.png => ./data_image/MT_Free/Imgs/test568.jpg
./data_image/MT_Free/Imgs/exp2_num_128095.jpg => ./data_image/MT_Free/Imgs/test569.png
./data_image/MT_Free/Imgs/exp2_num_128095.png => ./data_image/MT_Free/Imgs/test569.jpg
./data_image/MT_Free/Imgs/exp2_num_129608.jpg => ./data_image/MT_Free/Imgs/test570.png
./data_image/MT_Free/Imgs/exp2_num_129608.p

./data_image/MT_Free/Imgs/exp3_num_157763.png => ./data_image/MT_Free/Imgs/test737.jpg
./data_image/MT_Free/Imgs/exp3_num_165409.jpg => ./data_image/MT_Free/Imgs/test738.png
./data_image/MT_Free/Imgs/exp3_num_165409.png => ./data_image/MT_Free/Imgs/test738.jpg
./data_image/MT_Free/Imgs/exp3_num_16556.jpg => ./data_image/MT_Free/Imgs/test739.png
./data_image/MT_Free/Imgs/exp3_num_16556.png => ./data_image/MT_Free/Imgs/test739.jpg
./data_image/MT_Free/Imgs/exp3_num_166221.jpg => ./data_image/MT_Free/Imgs/test740.png
./data_image/MT_Free/Imgs/exp3_num_166221.png => ./data_image/MT_Free/Imgs/test740.jpg
./data_image/MT_Free/Imgs/exp3_num_174699.jpg => ./data_image/MT_Free/Imgs/test741.png
./data_image/MT_Free/Imgs/exp3_num_174699.png => ./data_image/MT_Free/Imgs/test741.jpg
./data_image/MT_Free/Imgs/exp3_num_177963.jpg => ./data_image/MT_Free/Imgs/test742.png
./data_image/MT_Free/Imgs/exp3_num_177963.png => ./data_image/MT_Free/Imgs/test742.jpg
./data_image/MT_Free/Imgs/exp3_num_178510.jpg

./data_image/MT_Free/Imgs/exp3_num_7899.png => ./data_image/MT_Free/Imgs/test867.jpg
./data_image/MT_Free/Imgs/exp3_num_91008.jpg => ./data_image/MT_Free/Imgs/test868.png
./data_image/MT_Free/Imgs/exp3_num_91008.png => ./data_image/MT_Free/Imgs/test868.jpg
./data_image/MT_Free/Imgs/exp3_num_913.jpg => ./data_image/MT_Free/Imgs/test869.png
./data_image/MT_Free/Imgs/exp3_num_913.png => ./data_image/MT_Free/Imgs/test869.jpg
./data_image/MT_Free/Imgs/exp3_num_94938.jpg => ./data_image/MT_Free/Imgs/test870.png
./data_image/MT_Free/Imgs/exp3_num_94938.png => ./data_image/MT_Free/Imgs/test870.jpg
./data_image/MT_Free/Imgs/exp4_num_10227.jpg => ./data_image/MT_Free/Imgs/test871.png
./data_image/MT_Free/Imgs/exp4_num_10227.png => ./data_image/MT_Free/Imgs/test871.jpg
./data_image/MT_Free/Imgs/exp4_num_106203.jpg => ./data_image/MT_Free/Imgs/test872.png
./data_image/MT_Free/Imgs/exp4_num_106203.png => ./data_image/MT_Free/Imgs/test872.jpg
./data_image/MT_Free/Imgs/exp4_num_10642.jpg => ./data_im

./data_image/MT_Free/Imgs/exp4_num_91034.jpg => ./data_image/MT_Free/Imgs/test1028.png
./data_image/MT_Free/Imgs/exp4_num_91034.png => ./data_image/MT_Free/Imgs/test1028.jpg
./data_image/MT_Free/Imgs/exp4_num_933.jpg => ./data_image/MT_Free/Imgs/test1029.png
./data_image/MT_Free/Imgs/exp4_num_933.png => ./data_image/MT_Free/Imgs/test1029.jpg
./data_image/MT_Free/Imgs/exp4_num_94954.jpg => ./data_image/MT_Free/Imgs/test1030.png
./data_image/MT_Free/Imgs/exp4_num_94954.png => ./data_image/MT_Free/Imgs/test1030.jpg
./data_image/MT_Free/Imgs/exp5_num_10250.jpg => ./data_image/MT_Free/Imgs/test1031.png
./data_image/MT_Free/Imgs/exp5_num_10250.png => ./data_image/MT_Free/Imgs/test1031.jpg
./data_image/MT_Free/Imgs/exp5_num_106221.jpg => ./data_image/MT_Free/Imgs/test1032.png
./data_image/MT_Free/Imgs/exp5_num_106221.png => ./data_image/MT_Free/Imgs/test1032.jpg
./data_image/MT_Free/Imgs/exp5_num_106824.jpg => ./data_image/MT_Free/Imgs/test1033.png
./data_image/MT_Free/Imgs/exp5_num_106824.pn

./data_image/MT_Free/Imgs/exp6_num_126419.jpg => ./data_image/MT_Free/Imgs/test1203.png
./data_image/MT_Free/Imgs/exp6_num_126419.png => ./data_image/MT_Free/Imgs/test1203.jpg
./data_image/MT_Free/Imgs/exp6_num_126888.jpg => ./data_image/MT_Free/Imgs/test1204.png
./data_image/MT_Free/Imgs/exp6_num_126888.png => ./data_image/MT_Free/Imgs/test1204.jpg
./data_image/MT_Free/Imgs/exp6_num_127730.jpg => ./data_image/MT_Free/Imgs/test1205.png
./data_image/MT_Free/Imgs/exp6_num_127730.png => ./data_image/MT_Free/Imgs/test1205.jpg
./data_image/MT_Free/Imgs/exp6_num_128176.jpg => ./data_image/MT_Free/Imgs/test1206.png
./data_image/MT_Free/Imgs/exp6_num_128176.png => ./data_image/MT_Free/Imgs/test1206.jpg
./data_image/MT_Free/Imgs/exp6_num_129718.jpg => ./data_image/MT_Free/Imgs/test1207.png
./data_image/MT_Free/Imgs/exp6_num_129718.png => ./data_image/MT_Free/Imgs/test1207.jpg
./data_image/MT_Free/Imgs/exp6_num_13689.jpg => ./data_image/MT_Free/Imgs/test1208.png
./data_image/MT_Free/Imgs/exp6_nu

In [4]:
def changeName(path):  # 사이즈 조정
    for filename in os.listdir(path):
        img = Image.open(path+filename)
        
        resize_img = img.resize((512,512))
        resize_img.save(path+'re'+filename)
        print(resize_img)
            

 
changeName('./data_image/function/')

<PIL.Image.Image image mode=L size=512x512 at 0x2220C7D1070>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A6612E0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661220>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661280>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661040>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A6612E0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image m

<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661220>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661040>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661220>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661280>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A6612E0>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image m

<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661220>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661040>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661280>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A6612E0>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661220>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image m

<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A6612E0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661280>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661220>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661040>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A6612E0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image m

<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A6612E0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661040>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661220>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661280>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A6612E0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image m

<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A6612E0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661280>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661040>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661220>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A6612E0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image m

<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661220>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661040>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661280>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A6612E0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661220>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image m

<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661280>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661220>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661040>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A6612E0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661280>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image m

<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661280>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661220>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A6612E0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661040>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661280>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image m

<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661280>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image m

<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image m

<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661280>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image m

<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A6612E0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image m

<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661040>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image m

<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image m

<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A6612E0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image m

<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661220>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image m

<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A661220>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220A676190>
<PIL.Image.Image image m

<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
<PIL.Image.Image image mode=L size=512x512 at 0x2220AEBD730>
<PIL.Image.Image image mode=L size=512x512 at 0x22209652DC0>
