In [0]:
%load_ext tensorboard

In [0]:
tensorboard --logdir='./drive/My Drive/training_unet/log'

In [0]:
!python3 './drive/My Drive/YouTube/youtube-002-pytorch-unet/train.py'

In [0]:
!python3 './drive/My Drive/YouTube/youtube-002-pytorch-unet/eval.py'

TEST: BATCH 0001 / 0001 | LOSS 0.3026
AVERAGE TEST: BATCH 0001 / 0001 | LOSS 0.3026


In [21]:
!python3 "/content/drive/My Drive/YouTube/youtube-002-pytorch-unet/train.py" \
--lr 1e-2 --batch_size 2 --num_epoch 300 \
--data_dir "/content/drive/My Drive/YouTube/youtube-002-pytorch-unet/datasets" \
--ckpt_dir "/content/drive/My Drive/YouTube/youtube-002-pytorch-unet/checkpoint_v2" \
--log_dir "/content/drive/My Drive/YouTube/youtube-002-pytorch-unet/log_v2" \
--result_dir "/content/drive/My Drive/YouTube/youtube-002-pytorch-unet/result_v2" \
--mode "test" \
--train_continue "off"

learning rate: 1.0000e-02
batch size: 2
number of epoch: 300
data dir: /content/drive/My Drive/YouTube/youtube-002-pytorch-unet/datasets
ckpt dir: /content/drive/My Drive/YouTube/youtube-002-pytorch-unet/checkpoint_v2
log dir: /content/drive/My Drive/YouTube/youtube-002-pytorch-unet/log_v2
result dir: /content/drive/My Drive/YouTube/youtube-002-pytorch-unet/result_v2
mode: test
TEST: BATCH 0001 / 0002 | LOSS 0.2314
TEST: BATCH 0002 / 0002 | LOSS 0.2141
AVERAGE TEST: BATCH 0002 / 0002 | LOSS 0.2141


In [1]:
import numpy as np
import pandas as pd

In [4]:
dir = np.load('label_000.npy')

In [5]:
print(dir)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
